apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: panel-recruitment-quality
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ required "ingress.cert_arn" .Values.ingress.cert_arn }}
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.path }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: panel-recruitment-quality
            port:
              name: http
