apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: panel-recruitment-quality
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: panel-recruitment-quality