apiVersion: v1
kind: Secret
metadata:
  name: panel-recruitment-quality-rds
type: Opaque
data:
  rds_app_token: {{ .Values.rds.appToken | b64enc }}
  rds_app_gateway: {{ .Values.rds.appGateway | b64enc }}
  rds_host: {{ .Values.rds.host | b64enc }}
  rds_username: {{ .Values.rds.username | b64enc }}
  rds_password: {{ .Values.rds.password | b64enc }}
  rds_google_client_id: {{ .Values.rds.googleClientID | b64enc }}
  rds_google_client_secret: {{ .Values.rds.googleClientSecret | b64enc }}
  rds_google_redirect_uri: {{ .Values.rds.googleRedirectUri | b64enc }}
  rds_gmail_access_token: {{ .Values.rds.gmailAccessToken | b64enc }}
  rds_gmail_refresh_token: {{ .Values.rds.gmailRefreshToken | b64enc }}
