apiVersion: v1
kind: Secret
metadata:
  name: panel-recruitment-quality-rds
type: Opaque
data:
  rds_host: {{ .Values.rds.host | b64enc }}
  rds_username: {{ .Values.rds.username | b64enc }}
  rds_password: {{ .Values.rds.password | b64enc }}