apiVersion: v1
kind: Service
metadata:
    name: panel-recruitment-quality
spec:
  selector: 
    app.kubernetes.io/name: panel-recruitment-quality
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http