image:
  registry: registry.gitlab.com/nielsen-media/panel-management/one-media-recruitment/panel-recruitment-quality
  tag: 

replicas: 2

healthcheck:
  path: /usremoterecqa/service/health_asd

container:
  port: 8070

ingress:
  cert_arn: 
  host: 

rds:
  host:
  username:
  password: