image:
  registry: registry.gitlab.com/nielsen-media/panel-management/one-media-recruitment/panel-recruitment-quality
  tag: 2.0.1

replicas: 2

healthcheck:
  path: /usremoterecqa/service/health

container:
  port: 8070

ingress:
  cert_arn: 
  host: 

rds:
  appToken:
  appGateway:
  host:
  username:
  password:
  googleClientID:  
  googleClientSecret:
  googleRedirectUri:
  gmailAccessToken:
  gmailRefreshToken:
  